### ISSUE TITLE
AppCenter crashes when deleting characters out of searches [$25]

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/appcenter#202]
For searches that return results with HumbleButton enabled Applications (e.g 'vocal'), when you delete characters out of the search using the backspace key, AppCenter segfaults after deleting one or two of the characters.

Issue looks to be with constructing the humble button in some way.

Backtrace from debug build below: 
<details>
```
#0  0x00007ffff51a2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff51a402a in __GI_abort () at abort.c:89
#2  0x00007ffff51e47ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff52fd2e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff51eed61 in malloc_printerr (ar_ptr=0x3, ptr=<optimized out>, 
    str=0x7ffff52fd710 "malloc(): smallbin double linked list corrupted", action=3) at malloc.c:5004
#4  _int_malloc (av=av@entry=0x7ffff5530b20 <main_arena>, bytes=bytes@entry=32) at malloc.c:3384
#5  0x00007ffff51f121a in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3234
#6  0x00007ffff5827771 in g_malloc0 () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff58107b5 in g_hash_table_new_full () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff6d985e5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff5b1c317 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff5afe31b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff5b001b5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff5b00521 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6dcc44e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff5b1c359 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff5afe31b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff5affc01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff5b00534 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6dcc4c9 in gtk_label_new () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff6ceeca5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff5afe897 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff5b001b5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff5b00521 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00000000004544eb in app_center_widgets_humble_button_get_amount_button (self=0x2a29170, amount=5)
    at /home/david/Documents/appcenter/src/Widgets/HumbleButton.vala:160
#24 0x0000000000455086 in app_center_widgets_humble_button_constructor (type=34623904, n_construct_properties=0, 
    construct_properties=0x0) at /home/david/Documents/appcenter/src/Widgets/HumbleButton.vala:89
#25 0x00007ffff5afead8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff5b001b5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff5b00521 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00000000004541a7 in app_center_widgets_humble_button_construct (object_type=34623904)
    at /home/david/Documents/appcenter/src/Widgets/HumbleButton.vala:81
#29 0x00000000004541c2 in app_center_widgets_humble_button_new () at /home/david/Documents/appcenter/src/Widgets/HumbleButton.vala:80
---Type <return> to continue, or q <return> to quit---
#30 0x00000000004491b2 in app_center_abstract_app_container_constructor (type=35045024, n_construct_properties=0, 
    construct_properties=0x0) at /home/david/Documents/appcenter/src/Widgets/AbstractAppContainer.vala:92
#31 0x00000000004515fe in app_center_widgets_package_row_abstract_package_row_grid_constructor (type=35045024, 
    n_construct_properties=0, construct_properties=0x0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:72
#32 0x0000000000452341 in app_center_widgets_package_row_list_package_row_grid_constructor (type=35045024, n_construct_properties=0, 
    construct_properties=0x0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:161
#33 0x00007ffff5afead8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff5affc01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff5b00534 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x000000000044823c in app_center_abstract_app_container_construct (object_type=35045024)
    at /home/david/Documents/appcenter/src/Widgets/AbstractAppContainer.vala:21
#37 0x000000000045142f in app_center_widgets_package_row_abstract_package_row_grid_construct (object_type=35045024, 
    package=0x113e6a0, size_group=0x1490040, show_uninstall=0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:93
#38 0x000000000045216d in app_center_widgets_package_row_list_package_row_grid_construct (object_type=35045024, package=0x113e6a0, 
    size_group=0x1490040, show_uninstall=0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:172
#39 0x00000000004521b6 in app_center_widgets_package_row_list_package_row_grid_new (package=0x113e6a0, size_group=0x1490040, 
    show_uninstall=0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:171
#40 0x0000000000450fe2 in app_center_widgets_package_row_construct_list (object_type=25368544, package=0x113e6a0, 
    size_group=0x1490040, show_uninstall=0) at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:34
#41 0x00000000004510bb in app_center_widgets_package_row_new_list (package=0x113e6a0, size_group=0x1490040, show_uninstall=0)
    at /home/david/Documents/appcenter/src/Widgets/PackageRow.vala:33
#42 0x000000000043e58b in app_center_views_app_list_view_real_make_row (base=0x15cdbb0, package=0x113e6a0)
    at /home/david/Documents/appcenter/src/Views/AppListView.vala:61
#43 0x000000000044ab64 in app_center_abstract_app_list_make_row (self=0x15cdbb0, package=0x113e6a0)
    at /home/david/Documents/appcenter/src/Widgets/AbstractAppList.vala:93
#44 0x000000000043e713 in app_center_views_app_list_view_show_more_apps (self=0x15cdbb0)
    at /home/david/Documents/appcenter/src/Views/AppListView.vala:69
#45 0x000000000043e3c4 in app_center_views_app_list_view_real_add_packages (base=0x15cdbb0, packages=0x1462bf0)
    at /home/david/Documents/appcenter/src/Views/AppListView.vala:43
#46 0x000000000044a3cd in app_center_abstract_app_list_add_packages (self=0x15cdbb0, packages=0x1462bf0)
    at /home/david/Documents/appcenter/src/Widgets/AbstractAppList.vala:52
#47 0x0000000000445bb6 in app_center_views_search_view_search_co (_data_=0x23c5ba0)
    at /home/david/Documents/appcenter/src/Views/SearchView.vala:48
#48 0x0000000000445a28 in app_center_views_search_view_search (self=0x1444880, search_term=0x1781b50 "voc", category=0x0, 
    _callback_=0x42b3bc <____lambda78__gasync_ready_callback>, _user_data_=0x147c2e0)
---Type <return> to continue, or q <return> to quit---
    at /home/david/Documents/appcenter/src/Views/SearchView.vala:23
#49 0x000000000042b8a2 in app_center_main_window_trigger_search (self=0x147c2e0)
    at /home/david/Documents/appcenter/src/MainWindow.vala:238
#50 0x000000000042a11e in __lambda77_ (self=0x147c2e0) at /home/david/Documents/appcenter/src/MainWindow.vala:68
#51 0x000000000042a13d in ___lambda77__gtk_search_entry_search_changed (_sender=0x11e6240, self=0x147c2e0)
    at /home/david/Documents/appcenter/src/MainWindow.vala:68
#52 0x00007ffff5af91d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007ffff5b139a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff5b1408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00007ffff6cc039a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#56 0x00007ffff5822ab3 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff582204a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007ffff58223f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff582249c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007ffff75abd6d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#61 0x00007ffff7b6f3e0 in granite_application_run () from /usr/lib/x86_64-linux-gnu/libgranite.so.3
#62 0x0000000000429fec in _vala_main (args=0x7fffffffdd18, args_length1=1) at /home/david/Documents/appcenter/src/Application.vala:242
#63 0x000000000042a035 in main (argc=1, argv=0x7fffffffdd18) at /home/david/Documents/appcenter/src/Application.vala:240
```
</details>

---
There's a bounty on this issue [on bountysource](https://www.bountysource.com/issues/43784952-appcenter-crashes-when-deleting-characters-out-of-searches)

**Comment by cassidyjames** [comment]
Just for completeness, the bug occurred when there was any character change (typing or backspacing) in the search once a humblebutton was rendered.
