### ISSUE TITLE
AppCenter gets stuck before showing window

### ISSUE THREAD

**Issue by ryonakano** [elementary/appcenter#2147]
### What Happened?

AppCenter seems to get stuck before showing window when launching.

### Steps to Reproduce

1. Open Terminal
2. Run `killall io.elementary.appcenter` to kill daemon in case of running
3. Run `io.elementary.appcenter`
4. See AppCenter is never shown

### Expected Behavior

AppCenter window should be shown.

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

### Log Output

```shell
user@VirtualBox-80f42681:~/work/appcenter$ io.elementary.appcenter > /dev/null 2&>1 &
[1] 3448
user@VirtualBox-80f42681:~/work/appcenter$ ps -p $(pgrep io.elementary.a) -Ll
F S   UID     PID    PPID     LWP  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
0 S  1000    3448    2804    3448  0  80   0 - 242728 futex_ pts/1   00:00:00 io.elementary.a
1 S  1000    3448    2804    3456  0  80   0 - 242728 futex_ pts/1   00:00:00 pool-spawner
1 S  1000    3448    2804    3457  0  80   0 - 242728 do_pol pts/1   00:00:00 gmain
1 S  1000    3448    2804    3458  0  80   0 - 242728 do_pol pts/1   00:00:00 dconf worker
1 S  1000    3448    2804    3459  0  80   0 - 242728 do_pol pts/1   00:00:00 gdbus
1 S  1000    3448    2804    3460  0  80   0 - 242728 futex_ pts/1   00:00:00 io.elementary.a
1 S  1000    3448    2804    3464  0  80   0 - 242728 futex_ pts/1   00:00:00 flatpak-worker
user@VirtualBox-80f42681:~/work/appcenter$ sudo gdb --pid=$(pgrep io.elementary.a)
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 3448
[New LWP 3464]
[New LWP 3460]
[New LWP 3459]
[New LWP 3458]
[New LWP 3457]
[New LWP 3456]

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libglib-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgobject-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/liblber.so.2

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgsttag-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstallocators-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstbase-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/liborc-0.4.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libtinfo.so.6

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38

warning: 38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory
(gdb) thread apply all bt

Thread 7 (Thread 0x7caab14006c0 (LWP 3456) "pool-spawner"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007caab777740d in g_cond_wait () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab76e852b in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007caab7750043 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#6  0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 6 (Thread 0x7caab0a006c0 (LWP 3457) "gmain"):
#0  0x00007caab5f1b4cd in __GI___poll (fds=0x64c4020e0c30, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007caab777d66e in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab771da53 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007caab771daa9 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#6  0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 5 (Thread 0x7caaa80006c0 (LWP 3458) "dconf worker"):
#0  0x00007caab5f1b4cd in __GI___poll (fds=0x7caa98000b90, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007caab777d66e in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab771da53 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007caab1f02595 in ??? () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#6  0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 4 (Thread 0x7caaa90006c0 (LWP 3459) "gdbus"):
#0  0x00007caab5f1b4cd in __GI___poll (fds=0x7caa94000b90, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007caab777d66e in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab771ef77 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007caab75a8422 in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#6  0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 3 (Thread 0x7caaa76006c0 (LWP 3460) "io.elementary.a"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007caab777740d in g_cond_wait () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab76e852b in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#3  0x00007caab76e858c in g_async_queue_pop () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007caab54ef0fb in ??? () at /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
#5  0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7caa9ee006c0 (LWP 3464) "flatpak-worker"):
#0  futex_wait (private=0, expected=2, futex_word=0x64c4020cd070) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x64c4020cd070, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007caab5ea0147 in lll_mutex_lock_optimized (mutex=0x64c4020cd070) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x64c4020cd070) at ./nptl/pthread_mutex_lock.c:128
#4  0x00007caab769e647 in g_type_class_ref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007caab7686162 in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007caab7686f71 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007caab63c6f04 in ??? () at /lib/x86_64-linux-gnu/libflatpak.so.0
#8  0x00007caab63928d9 in flatpak_installation_update_appstream_full_sync () at /lib/x86_64-linux-gnu/libflatpak.so.0
#9  0x00007caab6394ce9 in flatpak_installation_update_appstream_sync () at /lib/x86_64-linux-gnu/libflatpak.so.0
#10 0x000064c4006ab15e in app_center_core_flatpak_backend_preprocess_metadata (self=0x64c40239a9d0, system=0, remotes=0x64c4023bf4b0, cancellable=0x64c4023ae260) at ../src/Core/FlatpakBackend.vala:1045
#11 0x000064c4006aa2aa in app_center_core_flatpak_backend_refresh_cache_internal (self=0x64c40239a9d0, job=0x64c4031fd190) at ../src/Core/FlatpakBackend.vala:956
#12 0x000064c40069e3a2 in app_center_core_flatpak_backend_worker_func (self=0x64c40239a9d0) at ../src/Core/FlatpakBackend.vala:93
#13 0x000064c4006b952b in _app_center_core_flatpak_backend_worker_func_gthread_func (self=0x64c40239a9d0) at /home/user/work/appcenter/builddir/FlatpakBackend.c:16598
#14 0x00007caab774cc82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007caab5e9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#16 0x00007caab5f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7caab3d66500 (LWP 3448) "io.elementary.a"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007caab777740d in g_cond_wait () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007caab774361b in g_once_impl () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x000064c400695934 in app_center_core_backend_aggregator_get_default () at ../src/Core/BackendAggregator.vala:337
#4  0x000064c4006de278 in app_center_core_update_manager_constructor (type=Python Exception <class 'gdb.error'>: No type named TypeNode.
, n_construct_properties=0, construct_properties=0x0) at ../src/Core/UpdateManager.vala:37
#5  0x00007caab7684691 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007caab7685fc4 in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007caab7686f71 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x000064c4006ddd12 in app_center_core_update_manager_construct (object_type=Python Exception <class 'gdb.error'>: No type named TypeNode.
) at ../src/Core/UpdateManager.vala:20
#9  0x000064c4006ddd31 in app_center_core_update_manager_new () at ../src/Core/UpdateManager.vala:20
#10 0x000064c4006ddc63 in __lambda45_ () at ../src/Core/UpdateManager.vala:168
#11 0x000064c4006ddc8a in ___lambda45__gthread_func (self=0x0) at /home/user/work/appcenter/builddir/UpdateManager.c:1475
#12 0x00007caab774363d in g_once_impl () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x000064c4006ddcd2 in app_center_core_update_manager_get_default () at ../src/Core/UpdateManager.vala:168
#14 0x000064c4006ff5d0 in app_center_views_app_list_update_view_get_apps_co (_data_=0x64c40256a880) at ../src/Views/AppListUpdateView.vala:196
#15 0x000064c4006ff3e2 in app_center_views_app_list_update_view_get_apps_ready (source_object=0x0, _res_=0x64c403857b60, _user_data_=0x64c40256a880) at ../src/Views/AppListUpdateView.vala:193
#16 0x00007caab753f7ab in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007caab753f7e5 in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007caab771e48e in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007caab777d717 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007caab771ef77 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x000064c400737b1e in app_center_core_package_kit_backend_class_init (klass=0x64c4038568e0, klass_data=0x0) at ../src/Core/PackageKitBackend.vala:153
#22 0x00007caab769ea7d in g_type_class_ref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007caab7686162 in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007caab7686f71 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x000064c40072238d in app_center_core_package_kit_backend_construct (object_type=Python Exception <class 'gdb.error'>: No type named TypeNode.
) at ../src/Core/PackageKitBackend.vala:159
#26 0x000064c400722e6e in app_center_core_package_kit_backend_new () at ../src/Core/PackageKitBackend.vala:159
#27 0x000064c400737022 in __lambda59_ () at ../src/Core/PackageKitBackend.vala:1321
#28 0x000064c400737049 in ___lambda59__gthread_func (self=0x0) at /home/user/work/appcenter/builddir/PackageKitBackend.c:13238
#29 0x00007caab774363d in g_once_impl () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x000064c400737091 in app_center_core_package_kit_backend_get_default () at ../src/Core/PackageKitBackend.vala:1321
#31 0x000064c400695fb7 in app_center_core_backend_aggregator_constructor (type=Python Exception <class 'gdb.error'>: No type named TypeNode.
, n_construct_properties=0, construct_properties=0x0) at ../src/Core/BackendAggregator.vala:30
#32 0x00007caab7684691 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007caab7685fc4 in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007caab7686f71 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x000064c400695974 in app_center_core_backend_aggregator_construct (object_type=Python Exception <class 'gdb.error'>: No type named TypeNode.
) at ../src/Core/BackendAggregator.vala:20
#36 0x000064c400695993 in app_center_core_backend_aggregator_new () at ../src/Core/BackendAggregator.vala:20
#37 0x000064c4006958c5 in __lambda20_ () at ../src/Core/BackendAggregator.vala:337
#38 0x000064c4006958ec in ___lambda20__gthread_func (self=0x0) at /home/user/work/appcenter/builddir/BackendAggregator.c:3795
#39 0x00007caab774363d in g_once_impl () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x000064c400695934 in app_center_core_backend_aggregator_get_default () at ../src/Core/BackendAggregator.vala:337
#41 0x000064c400703bcb in app_center_views_app_list_update_view_constructor (type=Python Exception <class 'gdb.error'>: No type named TypeNode.
, n_construct_properties=1, construct_properties=0x7ffcf73d45d0) at ../src/Views/AppListUpdateView.vala:170
#42 0x00007caab76844e4 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007caab7685fc4 in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007caab7686f71 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x000064c400702325 in app_center_views_app_list_update_view_construct (object_type=Python Exception <class 'gdb.error'>: No type named TypeNode.
) at ../src/Views/AppListUpdateView.vala:24
#46 0x000064c400702344 in app_center_views_app_list_update_view_new () at ../src/Views/AppListUpdateView.vala:24
#47 0x000064c40068c646 in app_center_main_window_constructor (type=Python Exception <class 'gdb.error'>: No type named TypeNode.
, n_construct_properties=5, construct_properties=0x7ffcf73d4da0) at ../src/MainWindow.vala:197
--Type <RET> for more, q to quit, c to continue without paging--
#48 0x00007caab76844e4 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007caab768674a in g_object_new_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007caab7686f4f in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x000064c400687e91 in app_center_main_window_construct (object_type=Python Exception <class 'gdb.error'>: No type named TypeNode.
, app=0x64c4020e4720) at ../src/MainWindow.vala:39
#52 0x000064c4006882b3 in app_center_main_window_new (app=0x64c4020e4720) at ../src/MainWindow.vala:38
#53 0x000064c400683a7d in app_center_app_real_activate (base=0x64c4020e4720) at ../src/Application.vala:225
#54 0x00007caab76936bd in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00007caab76937c1 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#56 0x00007caab7693883 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#57 0x000064c400681c17 in app_center_app_real_open (base=0x64c4020e4720, files=0x64c4023bcc10, files_length1=1, hint=0x64c4023bcbf0 "") at ../src/Application.vala:64
#58 0x00007caab75097fb in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#59 0x00007caab76936bd in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#60 0x00007caab76937c1 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#61 0x00007caab7693883 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#62 0x00007caab7575622 in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#63 0x00007caab7575823 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#64 0x000064c400685fb0 in _vala_main (args=0x7ffcf73d6088, args_length1=2) at ../src/Application.vala:424
#65 0x000064c400685ff7 in main (argc=2, argv=0x7ffcf73d6088) at ../src/Application.vala:422
(gdb)
```

**Comment by leolost2605** [comment]
Seems this is caused by the packagekit backend for some reason. But since that's going to be removed anyways I didn't do anymore investigation :)
