### ISSUE TITLE
Fairly frequent crash shortly after opening AppCenter

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#347]
and I have a backtrace:

```
Starting program: /usr/bin/appcenter 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7973700 (LWP 7824)]
[New Thread 0x7fffe7172700 (LWP 7825)]
[New Thread 0x7fffe6971700 (LWP 7826)]
[INFO 21:04:39.652641] Application.vala:148: App Center version: 0.2.3
[INFO 21:04:39.652673] Application.vala:150: Kernel version: 4.4.0-81-generic
[WARNING 21:04:39.676033] [Gtk] Theme parsing error: gtk-widgets.css:2049:14: 'min-height' is not a valid property name
[WARNING 21:04:39.676081] [Gtk] Theme parsing error: gtk-widgets.css:2050:13: 'min-width' is not a valid property name
[WARNING 21:04:39.676116] [Gtk] Theme parsing error: gtk-widgets.css:2055:13: 'min-width' is not a valid property name
[WARNING 21:04:39.676420] [Gtk] Theme parsing error: gtk-widgets.css:2265:14: 'min-height' is not a valid property name
[WARNING 21:04:39.676450] [Gtk] Theme parsing error: gtk-widgets.css:2266:13: 'min-width' is not a valid property name
[New Thread 0x7fffd7df2700 (LWP 7829)]
[New Thread 0x7fffd55a4700 (LWP 7830)]
[New Thread 0x7fffd4b91700 (LWP 7832)]
[New Thread 0x7fffc7df8700 (LWP 7836)]
[New Thread 0x7fffc75f7700 (LWP 7837)]
[New Thread 0x7fffc6df6700 (LWP 7838)]
[Thread 0x7fffd4b91700 (LWP 7832) exited]
[Thread 0x7fffe7172700 (LWP 7825) exited]
[FATAL 21:04:44.597057] [Gtk] gtk_window_get_default_widget: assertion 'GTK_IS_WINDOW (window)' failed
[FATAL 21:04:44.598000] [Gtk] gtk_window_set_default: assertion 'GTK_IS_WINDOW (window)' failed
[New Thread 0x7fffe7172700 (LWP 7870)]
[Thread 0x7fffe7172700 (LWP 7870) exited]
[New Thread 0x7fffe7172700 (LWP 7912)]

Thread 9 "update-banner" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc75f7700 (LWP 7837)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff6cf1651 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff6d05413 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff6cf2b1c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff6d05309 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff6cf4ebd in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff6cf3f62 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff6cf4076 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff6e3e9a0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff6ee79f2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff6ee7dff in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff6eeabd8 in gtk_widget_set_parent () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff6c975cb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff5ab20a7 in g_cclosure_marshal_VOID__OBJECTv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff5aaf1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff5ac99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff5aca08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6ce0ca5 in gtk_container_add () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff6ca7bd8 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff6ca8f34 in gtk_button_set_label () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x0000000000437c1d in app_center_widgets_humble_button_set_amount ()
#21 0x0000000000430f8c in app_center_abstract_app_container_update_action ()
#22 0x00007ffff5aaefa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff5ac0fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff5ac9d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff5aca08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff5ab34d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff5ab5961 in g_object_notify () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x000000000042d7dc in ?? ()
#29 0x00007ffff57febb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff27406ba in start_thread (arg=0x7fffc75f7700) at pthread_create.c:333
#31 0x00007ffff52293dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by Philip-Scott** [comment]
If i were to guess, it's these blocks the ones giving the problems: https://github.com/elementary/appcenter/blob/master/src/Views/Homepage.vala#L82

It might be crashing due to a collision on this thread and the "apt-get update" thread
