### ISSUE TITLE
Appcenter segfaults in the constructor of StripeDialog due to incorrect Dutch translation

### ISSUE THREAD

**Issue by JMoerman** [elementary/appcenter#468]
_Pay $**%d**.00_ is currently translated to Dutch with _Betaal $ **%s**.00_ which seems to be causing segfaults.
For some reason I can only suggest translations, so I'm not able to fix it.

See dmesg trace:
```
Thread 1 "appcenter" received signal SIGSEGV, Segmentation fault.
0x00007ff6442e4cc0 in _IO_vfprintf_internal (s=s@entry=0x7fffffffbee0, format=<optimized out>, format@entry=0x7ff647125192 "Betaal $ %s.00", ap=ap@entry=0x7fffffffc040) at vfprintf.c:1632
1632	vfprintf.c: Bestand of map bestaat niet.
(gdb) backtrace
#0  0x00007ff6442e4cc0 in _IO_vfprintf_internal (s=s@entry=0x7fffffffbee0, format=<optimized out>, format@entry=0x7ff647125192 "Betaal $ %s.00", ap=ap@entry=0x7fffffffc040) at vfprintf.c:1632
#1  0x00007ff6443ae975 in __GI___vasprintf_chk (result_ptr=result_ptr@entry=0x7fffffffc020, flags=flags@entry=1, format=0x7ff647125192 "Betaal $ %s.00", format@entry=0x7fffffffc020 "", args=0x7fffffffc040) at vasprintf_chk.c:66
#2  0x00007ff64498fc99 in g_vasprintf (__ap=<optimized out>, __fmt=<optimized out>, __ptr=0x7fffffffc020) at /usr/include/x86_64-linux-gnu/bits/stdio2.h:210
#3  0x00007ff64498fc99 in g_vasprintf (string=string@entry=0x7fffffffc020, format=<optimized out>, args=args@entry=0x7fffffffc040) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gprintf.c:316
#4  0x00007ff64496a66d in g_strdup_vprintf (format=<optimized out>, args=args@entry=0x7fffffffc040) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gstrfuncs.c:514
#5  0x00007ff64496a729 in g_strdup_printf (format=<optimized out>) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gstrfuncs.c:540
#6  0x0000000000428c07 in  ()
#7  0x00007ff644c28149 in g_object_new_internal (n_params=6, params=0x7fffffffc3f0, class=0x2f69240) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1699
#8  0x00007ff644c28149 in g_object_new_internal (class=class@entry=0x2f69240, params=params@entry=0x7fffffffc3f0, n_params=n_params@entry=6) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1779
#9  0x00007ff644c2a1b5 in g_object_new_valist (object_type=object_type@entry=49609040, first_property_name=first_property_name@entry=0x4420fa "amount", var_args=var_args@entry=0x7fffffffc540)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:2040
#10 0x00007ff644c2a521 in g_object_new (object_type=49609040, first_property_name=0x4420fa "amount") at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1624
#11 0x0000000000427e37 in app_center_widgets_stripe_dialog_construct ()
#12 0x0000000000431968 in  ()
#13 0x00007ff644c25518 in g_cclosure_marshal_VOID__ENUMv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x2356120) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gmarshal.c:1496
#14 0x00007ff644c231d4 in _g_closure_invoke_va (closure=closure@entry=0x24cffd0, return_value=return_value@entry=0x0, instance=instance@entry=0x2f5bf80, args=args@entry=0x7fffffffc958, n_params=<optimized out>, param_types=0x2356120)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:867
#15 0x00007ff644c3d9a6 in g_signal_emit_valist (instance=instance@entry=0x2f5bf80, signal_id=signal_id@entry=382, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffc958)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3294
#16 0x00007ff644c3e555 in g_signal_emit_by_name (instance=0x2f5bf80, detailed_signal=0x445608 "payment-requested") at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3481
#17 0x00007ff644c231d4 in _g_closure_invoke_va (closure=closure@entry=0x2fcc180, return_value=return_value@entry=0x0, instance=instance@entry=0x2f501c0, args=args@entry=0x7fffffffcca0, n_params=<optimized out>, param_types=0x0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:867
#18 0x00007ff644c3d9a6 in g_signal_emit_valist (instance=0x2f501c0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffcca0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3294
#19 0x00007ff644c3e08f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3441
#20 0x00007ff645e206ad in gtk_button_do_release (button=0x2f501c0 [GtkButton], emit_clicked=<optimized out>) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkbutton.c:1899
#21 0x00007ff645e20715 in gtk_real_button_released (button=0x2f501c0 [GtkButton]) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkbutton.c:2017
#25 0x00007ff644c3e08f in <emit signal ??? on instance 0x2f501c0 [GtkButton]> (instance=instance@entry=0x2f501c0, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3441
    #22 0x00007ff644c22fa5 in g_closure_invoke (closure=closure@entry=0x155de90, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffcfa0, invocation_hint=invocation_hint@entry=0x7fffffffcf20)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:804
    #23 0x00007ff644c34afc in signal_emit_unlocked_R (node=node@entry=0x151ea60, detail=detail@entry=0, instance=instance@entry=0x2f501c0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffcfa0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3559
    #24 0x00007ff644c3dd5c in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd150) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3385
#26 0x00007ff645e1e7a0 in multipress_released_cb (gesture=0x2f4a120 [GtkGestureMultiPress], n_press=<optimized out>, x=<optimized out>, y=<optimized out>, widget=0x2f501c0 [GtkButton])
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkbutton.c:613
#27 0x00007ff63f272e40 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#28 0x00007ff63f2728ab in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#29 0x00007ff644c23cf5 in g_cclosure_marshal_generic_va (closure=0x2f420c0, return_value=0x0, instance=0x2f4a120, args_list=<optimized out>, marshal_data=0x0, n_params=3, param_types=0x151d1e0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:1604
#30 0x00007ff644c231d4 in _g_closure_invoke_va (closure=closure@entry=0x2f420c0, return_value=return_value@entry=0x0, instance=instance@entry=0x2f4a120, args=args@entry=0x7fffffffd730, n_params=<optimized out>, param_types=0x151d1e0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:867
#31 0x00007ff644c3d9a6 in g_signal_emit_valist (instance=0x2f4a120, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd730) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3294
#32 0x00007ff644c3e08f in g_signal_emit (instance=instance@entry=0x2f4a120, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3441
#33 0x00007ff645ecc891 in gtk_gesture_multi_press_end (gesture=0x2f4a120 [GtkGestureMultiPress], sequence=<optimized out>) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkgesturemultipress.c:273
#34 0x00007ff644c25dbe in g_cclosure_marshal_VOID__BOXEDv (closure=0x161bf90, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x1565330)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gmarshal.c:1950
#35 0x00007ff644c231d4 in _g_closure_invoke_va (closure=closure@entry=0x161bf90, return_value=return_value@entry=0x0, instance=instance@entry=0x2f4a120, args=args@entry=0x7fffffffdac0, n_params=<optimized out>, param_types=0x1565330)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:867
#36 0x00007ff644c3d9a6 in g_signal_emit_valist (instance=0x2f4a120, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffdac0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3294
#37 0x00007ff644c3e08f in g_signal_emit (instance=instance@entry=0x2f4a120, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3441
#38 0x00007ff645ec9bee in _gtk_gesture_check_recognized (sequence=0x0, recognized=0, gesture=0x2f4a120 [GtkGestureMultiPress]) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkgesture.c:345
#39 0x00007ff645ec9bee in _gtk_gesture_check_recognized (gesture=gesture@entry=0x2f4a120 [GtkGestureMultiPress], sequence=sequence@entry=0x0) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkgesture.c:386
#40 0x00007ff645ecb22b in gtk_gesture_handle_event (controller=0x2f4a120 [GtkGestureMultiPress], event=0x2f29490) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkgesture.c:777
#41 0x00007ff645ecdde5 in gtk_gesture_single_handle_event (controller=0x2f4a120 [GtkGestureMultiPress], event=0x2f29490) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkgesturesingle.c:221
#42 0x00007ff645e9dbeb in gtk_event_controller_handle_event (controller=0x2f4a120 [GtkGestureMultiPress], event=event@entry=0x2f29490) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkeventcontroller.c:230
#43 0x00007ff64604ebfb in _gtk_widget_run_controllers (widget=0x2f501c0 [GtkButton], event=0x2f29490, phase=GTK_PHASE_BUBBLE) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:7321
#44 0x00007ff645f1309a in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x11d4a80, return_value=0x7fffffffde50, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x11d4ab0)
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmarshalers.c:131
#45 0x00007ff644c231d4 in _g_closure_invoke_va (closure=closure@entry=0x11d4a80, return_value=return_value@entry=0x7fffffffde50, instance=instance@entry=0x2f501c0, args=args@entry=0x7fffffffdf20, n_params=<optimized out>, param_types=0x11d4ab0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gclosure.c:867
#46 0x00007ff644c3d4b8 in g_signal_emit_valist (instance=0x2f501c0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffdf20) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3294
#47 0x00007ff644c3e08f in g_signal_emit (instance=instance@entry=0x2f501c0, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gsignal.c:3441
#48 0x00007ff646050c3c in gtk_widget_event_internal (widget=0x2f501c0 [GtkButton], event=0x2f29490) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:7692
#49 0x00007ff645f103be in propagate_event (topmost=<optimized out>, event=<optimized out>, widget=0x2f501c0 [GtkButton]) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmain.c:2527
```
Sorry for the long trace.

How to reproduce:
Run appcenter with Dutch locale and attempt to buy (is that the correct term, or is it donating?) an application. After clicking on the default amount or selecting any other amount appcenter will immidiately crash.

Running appcenter using
`LANG=en_US.UTF-8 LANGUAGE=en appcenter`
does not cause the bug.

**Comment by tintou** [comment]
Seems like there is a suggested change for this
https://l10n.elementary.io/translate/appcenter/appcenter/nl/?type=suggestions

**Comment by JMoerman** [comment]
@tintou I suggested it prior to creating this issue.
I used to be able to do more than just suggesting, if I recall correctlym but currently that's all I can do.

**Comment by DDieter** [comment]
@JMoerman I accepted the translation. With weblate it has indeed changed that you can only do suggestions, but I check them daily.

**Comment by JMoerman** [comment]
@DDieter as long as it is checked regularly that should be fine.
This bug must have been here for months as the format string was changed from _"Pay $%s.00"_ to _"Pay $%d.00"_ with https://github.com/elementary/appcenter/commit/f89bc0bb2540895eadd07f07e37813a81d4cf8a5 
A quick search shows that th same problem exists in multiple other translations:
ar ca hr hu ja kv nb nn ru sk uk
There may be more, but that was what I could find.

**Comment by DDieter** [comment]
All translations are updated, so this crash shouldn't happen anymore.

**Comment by JMoerman** [comment]
That is good to hear!
